let myString='test string';
let myNum=123;
let myBool=true;
let myNull=null;
let myUndefined;
console.log("This is: "+ myString);
console.log("This is number: "+ myNum);
console.log("This is boolean: "+ myBool);
console.log("This is null: "+ myNull);
console.log("This is undefined: "+ myUndefined);